NATO_CODE = {'A': 'Alfa',
             'B': 'Bravo',
             'C': 'Charlie',
             'D': 'Delta',
             'E': 'Echo',
             'F': 'Foxtrot',
             'G': 'Golf',
             'H': 'Hotel',
             'I': 'India',
             'J': 'Juliet',
             'K': 'Kilo',
             'L': 'Lima',
             'M': 'Mike',
             'N': 'November',
             'O': 'Oscar',
             'P': 'Papa',
             'Q': 'Quebec',
             'R': 'Romeo',
             'S': 'Sierra',
             'T': 'Tango',
             'U': 'Uniform',
             'V': 'Victor',
             'W': 'Whiskey',
             'X': 'X-ray',
             'Y': 'Yankee',
             'Z': 'Zulu'}

MORSE_CODE = {
    'A': '•-',
    'B': '-•••',
    'C': '-•-•',
    'D': '-••',
    'E': '•',
    'F': '••-•',
    'G': '--•',
    'H': '••••',
    'I': '••',
    'J': '•---',
    'K': '-•-',
    'L': '•-••',
    'M': '--',
    'N': '-•',
    'O': '---',
    'P': '•--•',
    'Q': '--•-',
    'R': '•-•',
    'S': '•••',
    'T': '-',
    'U': '••-',
    'V': '•••-',
    'W': '•--',
    'X': '-••-',
    'Y': '-•--',
    'Z': '--••',
    '1': '•----',
    '2': '••---',
    '3': '•••--',
    '4': '••••-',
    '5': '•••••',
    '6': '-••••',
    '7': '--•••',
    '8': '---••',
    '9': '----•',
    '0': '-----',
    '.': '•-•-•-',
    ',': '--••--',
    '?': '••--••',
    ':': '---•••',
    ';': '-•-•-•',
    "'": '•----•',
    '"': '•-••-•',
    '(': '-•--•',
    ')': '-•--•-',
    '/': '-••-•',
    '-': '-••••-',
    '=': '-•••-',
    '+': '•-•-•',
    '!': '-•-•--',
    '×': '-••-',
    '@': '•--•-•',
    ' ': ' '
    }

MORSE_AUDIO_DICT = {
    'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd', 'e': 'e', 'f': 'f',
    'g': 'g', 'h': 'h', 'i': 'i', 'j': 'j', 'k': 'k', 'l': 'l',
    'm': 'm', 'n': 'n', 'o': 'o', 'p': 'p', 'q': 'q', 'r': 'r',
    's': 's', 't': 't', 'u': 'u', 'v': 'v', 'w': 'w', 'x': 'x',
    'y': 'y', 'z': 'z', '1': '1', '2': '2', '3': '3',
    '4': '4', '5': '5', '6': '6', '7': '7', '8': '8',
    '9': '9', '0': '0', ' ': 'space', '.': 'period', ',': 'comma',
    '?': 'question', ':': 'colon', ';': 'semicolon', "'": 'apostrophe',
    '"': 'quote','(': 'lparenthesis', ')': 'rparenthesis', '/': 'divide',
    '-': 'minus', '=': 'equal', '+': 'plus', '!': 'exclamation',
    '×': 'multiply', '@': 'atsign',
}

BRAILLE = {
    'a': '⠁',
    'b': '⠃',
    'c': '⠉',
    'd': '⠙',
    'e': '⠑',
    'f': '⠋',
    'g': '⠛',
    'h': '⠓',
    'i': '⠊',
    'j': '⠚',
    'k': '⠅',
    'l': '⠇',
    'm': '⠍',
    'n': '⠝',
    'o': '⠕',
    'p': '⠏',
    'q': '⠟',
    'r': '⠗',
    's': '⠎',
    't': '⠞',
    'u': '⠥',
    'v': '⠧',
    'w': '⠺',
    'x': '⠭',
    'y': '⠽',
    'z': '⠵',
    ' ': ' ',
    '1': '⠁',
    '2': '⠃',
    '3': '⠉',
    '4': '⠙',
    '5': '⠑',
    '6': '⠋',
    '7': '⠛',
    '8': '⠓',
    '9': '⠊',
    '0': '⠚',
    ',': '⠂',
    '.': '⠲',
    '?': '⠹',
    '!': '⠖',
    '"': '⠦',
    '-': '⠤',
    '=': '⠐⠶',
    '+': '⠬',
    "'": '⠄',
    ';': '⠆',
    ':': '⠒',
    '(': '⠷',
    ')': '⠾',
    '/': '⠌',
    '@': '⠈',
    '*': '⠡',
    '×': '⠰'
}

TRIVIA_CATEGORIES = {'Any Category': 'any', 'General Knowledge': '9', 'Entertainment: Books': '10', 'Entertainment: Film': '11', 'Entertainment: Music': '12', 'Entertainment: Musicals & Theatres': '13', 'Entertainment: Television': '14', 'Entertainment: Video Games': '15', 'Entertainment: Board Games': '16', 'Science & Nature': '17', 'Science: Computers': '18', 'Science: Mathematics': '19', 'Mythology': '20', 'Sports': '21', 'Geography': '22', 'History': '23', 'Politics': '24', 'Art': '25', 'Celebrities': '26', 'Animals': '27', 'Vehicles': '28', 'Entertainment: Comics': '29', 'Science: Gadgets': '30', 'Entertainment: Japanese Anime & Manga': '31', 'Entertainment: Cartoon & Animations': '32'}
TRIVIA_DIFFICULTY = {'Easy': 'easy', 'Medium': 'medium', 'Hard': 'hard'}
TRIVIA_TYPE = {'Boolean': 'boolean', 'Multiple Choice': 'multiple'}
TRIVIA_QUESTION_COUNT = [10, 20, 30, 40, 50]
